-- 1. CRIAÇÃO DAS TABELAS no Supabase - Seguir esta ordem (usuarios, pacientes, agendamento, prontuarios, evolucoes)

create table public.usuarios (
    id bigint generated by default as identity not null,
    nome character varying(100) not null,
    login character varying(50) not null,
    senha character varying(100) not null,
    crp character varying(20) null,
    perfil character varying(30) not null,
    criado_em timestamp without time zone null default now(),
    status_ativo boolean not null default true,
    primeiro_acesso boolean null default true,
    constraint usuarios_pkey primary key (id),
    constraint usuarios_login_key unique (login)
);

create table public.pacientes ( 
    id bigint generated by default as identity not null, 
    nome character varying(100) not null, 
    cpf character varying(14) not null, 
    data_nascimento date not null, 
    telefone character varying(20) null, 
    criado_em timestamp without time zone null default now(), 
    constraint pacientes_pkey primary key (id), 
    constraint pacientes_cpf_key unique (cpf) 
);

create table public.agendamento (
    id serial not null,
    data_hora timestamp without time zone not null,
    status character varying(50) not null,
    paciente_id integer not null,
    usuario_id integer not null,
    constraint agendamento_pkey primary key (id),
    constraint agendamento_paciente_id_fkey foreign key (paciente_id) references pacientes (id) on delete cascade,
    constraint agendamento_usuario_id_fkey foreign key (usuario_id) references usuarios (id) on delete cascade
);

create table public.prontuarios (
    id bigint generated by default as identity not null,
    paciente_id bigint not null,
    constraint prontuarios_pkey primary key (id),
    constraint prontuarios_paciente_id_key unique (paciente_id),
    constraint prontuarios_paciente_id_fkey foreign key (paciente_id) references pacientes (id) on delete cascade
);

create table public.evolucoes (
    id bigint generated by default as identity not null,
    prontuario_id bigint not null,
    usuario_id bigint not null,
    texto_registro text not null,
    data_hora timestamp without time zone null default now(),
    constraint evolucoes_pkey primary key (id),
    constraint evolucoes_prontuario_id_fkey foreign key (prontuario_id) references prontuarios (id) on delete cascade,
    constraint evolucoes_usuario_id_fkey foreign key (usuario_id) references usuarios (id)
);